# -*- coding: utf-8 -*-
"""Trí Tuệ Nhân Tạo 06/09/2022

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZSirnwSMUMpjd8PgvLeckMz7vEu3mcD
"""

with open ('text.txt', mode="w") as accounts:
  accounts.write ('1 Nguyen Van A 8.0\n')
  accounts.write ('2 Le Thi B 6.8\n')

with open ('text1.txt', mode='w') as accounts:
  print('7:00 Nguyen Van A', file = accounts)
  print('7:01 Le Thi B', file = accounts)

with open ('text.txt', mode="r") as accounts:
  print (f'{'name':<20}{'score':>20}')
  for record in accounts:
    name, score = record.split()
    print(f'{name:<20}{score:>20}')

import pandas as pd
url = 'abc.csv'
dataframe = pd.read_csv(url)
dataframe.head(4)

import pandas as pd
dataframe = pd.DataFrame()
dataframe ['Name'] = ['Nguyen Thi Thuy Trang','Nguyen Tran Thanh Nhu']
dataframe ['Student ID'] = [20104063,20104049]
dataframe ['Score']=[9.0,9.5]
dataframe

import pandas as pd
url = '123.csv'
dataframe = pd.read_csv(url)
dataframe.head(10)

import pandas as pd
url = '123.csv'
dataframe = pd.read_csv(url)
#dataframe.head(10)
dataframe.iloc[0:8]

import pandas as pd
url = '123.csv'
dataframe = pd.read_csv(url)
#dataframe.head(10)
dataframe = dataframe.set_index(dataframe['Ho va Ten'])
dataframe.loc['Nguyen Thi Thuy Trang']

import pandas as pd
url = '456.csv'
dataframe = pd.read_csv(url)
#dataframe.head(10)
dataframe = dataframe.set_index(dataframe['Ho va Ten'])
dataframe.loc['Nguyen Thi Thuy Trang']

import pandas as pd
url = '456.csv'
dataframe = pd.read_csv(url)
dataframe[dataframe['Khoa']=='CKM'].head(5)

import pandas as pd
url = '456.csv'
dataframe = pd.read_csv(url)
dataframe[dataframe['Ho va Ten']=='Nguyen Thi Thuy Trang'].head(5)

import pandas as pd
url = '456.csv'
dataframe = pd.read_csv(url)
dataframe[(dataframe['Khoa']=='CKM') & (dataframe['Nam']==2020) & (dataframe['Diem']>= 9)].head(7)

import pandas as pd
url = '456.csv'
dataframe = pd.read_csv(url)
dataframe['Khoa'].unique()

import pandas as pd
url = '456.csv'
dataframe = pd.read_csv(url)
dataframe.drop('Khoa',axis=1).head(5)

import pandas as pd
url = '456.csv'
dataframe = pd.read_csv(url)
dataframe.groupby(dataframe['Diem']>= 8).count()

import pandas as pd
url = 'medals.csv'
data = pd.read_csv(url)
data. head(10)

import pandas as pd
url = 'medals.csv'
data = pd.read_csv(url)
data. head(10)
data['NOC'].unique()

import pandas as pd
url = 'medals.csv'
data = pd.read_csv(url)
data[(data['Medal']=='Gold') & (data['NOC']=='USA') & (data['Year']>= 2000)]

import pandas as pd
url = 'medals.csv'
data = pd.read_csv(url)
data.groupby((data['Medal']=='Gold') & (data['NOC']=='USA') & (data['Year']>= 2000)).count()

