# -*- coding: utf-8 -*-
"""Trí Tuệ Nhân Tạo 13/09/2022

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OmYNSLUtBdSUyEjUwQmUBNGTWBAlO4Fr
"""

from openpyxl import Workbook 
wb= Workbook()
sheet=wb.active 
sheet["A1"] = "Nguyen Tran Thanh Nhu"
sheet["B1"] = "20104049"
sheet["A2"] = "Nguyen Thi Thuy Trang"
sheet["B2"] = "20104063"
wb.save('test.xlsx')

import openpyxl 
wb = openpyxl.load_workbook('test.xlsx')
sheet= wb.active
t1=sheet["A1"]
t2=sheet["B1"]
t3=sheet.cell(row=2,column=1)
t4=sheet.cell(row=2,column=2)
print(t1.value, t2.value)
print(t3.value, t4.value)

import openpyxl
wb = openpyxl.Workbook()
sheet = wb.active
c1 = sheet.cell(row=1, column=1)
c1.value = "Nguyen Thi Thuy Trang"
c2 = sheet.cell(row=1, column=2)
c2.value = "Nguyen Tran Thanh Nhu"
c3 = sheet['A2']
c3.value = "20104063"
c4 = sheet['B2']
c4.value = "20104049"
wb.save("test1.xlsx")

import openpyxl
wb = openpyxl.Workbook()
sheet = wb. active
wb.create_sheet(index=1,title="CDT")
wb.save("test2.xlsx")

import openpyxl
path = "test1.xlsx"
wb_obj = openpyxl.load_workbook(path)
sheet_obj = wb_obj.active
print(sheet_obj.max_row)

cell_obj = sheet_obj.cell(row=1,column=1)
print(cell_obj.value)

import openpyxl
path = "test1.xlsx"
wb_obj= openpyxl.load_workbook(path)
sheet_obj = wb_obj.active
print(sheet_obj.max_column)

import openpyxl
path = "test1.xlsx"
wb_obj = openpyxl.load_workbook(path)
sheet_obj = wb_obj.active
max_col = sheet_obj.max_column
for i in range(1,max_col + 1):
  my_cell_obj = sheet_obj.cell(row=1, column=i)
  print(my_cell_obj.value)

import openpyxl
path = "test1.xlsx"
wb_obj = openpyxl.load_workbook(path)
sheet_obj = wb_obj.active
max_col = sheet_obj.max_row
for i in range(1,max_col + 1):
  my_cell_obj = sheet_obj.cell(row=i, column=1)
  print(my_cell_obj.value)

import openpyxl
path = "test1.xlsx"
wb_obj = openpyxl.load_workbook(path)
sheet_obj = wb_obj.active
max_col = sheet_obj.max_column
for i in range(1,max_col + 1):
  my_cell_obj = sheet_obj.cell(row=2, column=i)
  print(my_cell_obj.value)

import numpy as np
vector_row = np.array([1,2,3])
vector_column = np.array([[1],[2],[3]]) 

vector_row
vector_column

import numpy as np
matrix = np.array([[1,2],[1,2],[1,2]])
matrix

nhan_ba=lambda a: a*3
nhan_ba(10)

import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
add_100 = lambda i: i+100
add_100(10)

import matplotlib.pyplot as plt
import numpy as np
x=np.arange(6)
y=x+1
plt.plot(x,y,"o--")
plt.show

plt.plot(x,y,"o--", color = "green")
plt.plot(x,-y,"o-", color ="yellow")
plt.show()

plt.plot(x,y,"o--", color = "green")
plt.plot(x,-y,"o-", color ="yellow")
plt.title("y=x và y=-x")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

N=16
x=np.linspace (0,15,16)
y=x
plt.plot(x,y,"o--")
plt.axis("off")
plt.show()

N=16
x=np.linspace (0,15,16)
y=np.logspace (0.1,2,16)
plt.plot(x,y,"--o")
plt.show()

x=[4,5,3,1,6,7]
plt.plot(x)
plt.show()

x=np.arange(25)
plt.plot(x)
plt.show()

x=np.arange (25)
plt.plot(x,x**3+1)
plt.show()

x=np.arange(7)
plt.plot(x,-x**2)
plt.plot(x,-x**3)
plt.plot(x,-2*x)
plt.plot(x,-2**x)
plt.show()

x=np.arange(7)
plt.plot(x,-x**2,x,-x**3,x,-2*x,x,-2**x)
plt.show()

x=np.arange(7)
plt.plot(x,-x**2,'-',x,-x**3,'--',x,-2*x,'-o',x,-2**x,':')
plt.grid(True)
plt.savefig("test.png")
plt.show()

x=np.arange (3)
plt.subplots_adjust(wspace=0.3, hspace=0.3)
plt.subplot(2,2,1)
plt.plot(x,-x**2, color="green")
plt.subplot(2,2,2)
plt.plot(x,-x**3, color="yellow")
plt.subplot(2,2,3)
plt.plot(x,-2*x, color="blue")
plt.subplot(2,2,4)
plt.plot(x,-x**3, color="orange")
plt.show()

plt.axis([0,100,0,10])
plt.scatter(40,5,1000,color="green",alpha=1)
plt.scatter(60,5,s=1000,color="blue",alpha=.5)
plt.scatter(80,5,s=1000,color="black",alpha=.1)
plt.show()

plt.plot([5,10],[7,14],linewidth=5,color='green')
plt.text(5,10,"text", color="red",size=40)
plt.show()

plt.arrow(0.5,0.5,0,-0.5, head_length=4, head_width=2, color="g")
plt.show()

x=np.arange(4)
y=np.random.rand(4)
plt.bar(x,y)
plt.show()

y=np.random.rand(3,4)
plt.bar(x+0,y[0],color="black",width=0.25)
plt.bar(x+0.25,y[1],color= "red",width=0.25)
plt.bar(x+0.5,y[2],color="green",width=0.25)
plt.show()

x=np.arange(4)
y=np.random.rand(4)
plt.barh(x,y,color="pink")
plt.show()

y=np.random.rand(3,4)
plt.barh(x+0,y[0],color="black",height=0.25)
plt.barh(x+0.25,y[1],color= "red",height=0.25)
plt.barh(x+0.5,y[2],color="green",height=0.25)
plt.show()

N=1000
x=np.random.rand(N)
y=np.random.rand(N)
colors=np.random.rand(N)
size=20
plt.scatter(x,y,s=size,c=colors,alpha=1)
plt.show()

