# -*- coding: utf-8 -*-
"""Trí Tuệ Nhân Tạo 20/09/2022

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H0xc4eMOdZ8RB49Y5zPt8VIj7TQxwSn6
"""

pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
x = np.arange(11)
mfx = fuzz.trimf(x,[0,5,10])
#tạo tam giác có đỉnh tại vị trí x=5
x 
mfx

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
food = ctrl.Antecedent(np.arange(0,11,1),'food')
service = ctrl.Antecedent(np.arange(0,11,1),'service')
tip = ctrl.Consequent(np.arange(10,26,1),'tip')
#Antecedent:đầu vào
#Consequent:kết quả 
food['poor'] = fuzz.trimf(food.universe,[0,0,5])
food['average'] = fuzz.trimf(food.universe,[0,5,10])
food['good'] = fuzz.trimf(food.universe,[5,10,10])
service['poor'] = fuzz.trimf(service.universe,[0,0,5])
service['average'] = fuzz.trimf(service.universe,[0,5,10])
service['good'] = fuzz.trimf(service.universe,[5,10,10])
tip['less'] = fuzz.trimf(tip.universe,[10,14,18])
tip['normal'] = fuzz.trimf(tip.universe,[14,18,22])
tip['much'] = fuzz.trimf(tip.universe,[18,22,25])
food.view()
service.view()
tip.view()

rule1 =  ctrl.Rule( food['poor'] & service['poor'], tip['less'])
rule2 =  ctrl.Rule( food['poor'] & service['average'], tip['less'])
rule3 =  ctrl.Rule( food['poor'] & service['good'], tip['normal'])
rule4 =  ctrl.Rule( food['average'] & service['poor'], tip['less'])
rule5 =  ctrl.Rule( food['average'] & service['average'], tip['normal'])
rule6 =  ctrl.Rule( food['average'] & service['good'], tip['much'])
rule7 =  ctrl.Rule( food['good'] & service['poor'], tip['normal'])
rule8 =  ctrl.Rule( food['good'] & service['average'], tip['much'])
rule9 =  ctrl.Rule( food['good'] & service['good'], tip['much'])
tipping_ctrl = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,rule6,rule7,rule8,rule9])
tipping = ctrl.ControlSystemSimulation(tipping_ctrl)
tipping.input['food'] = 0
tipping.input['service'] = 1
tipping.compute()
print(tipping.output['tip'])
tip.view(sim=tipping)

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
time = ctrl.Antecedent(np.arange(10,121,5),'time')
rice = ctrl.Antecedent(np.arange(100,1001,5),'rice')
power = ctrl.Consequent(np.arange(0,101,5),'power')
#Antecedent:đầu vào
#Consequent:kết quả 
time['very slow'] = fuzz.trimf(time.universe,[10,10,40])
time['slow'] = fuzz.trimf(time.universe,[10,40,70])
time['medium'] = fuzz.trimf(time.universe,[40,70,100])
time['fast'] = fuzz.trimf(time.universe,[70,100,120])
time['very fast'] = fuzz.trimf(time.universe,[100,120,120])
rice['few'] = fuzz.trimf(rice.universe,[100,100,300])
rice['little'] = fuzz.trimf(rice.universe,[100,300,500])
rice['medium'] = fuzz.trimf(rice.universe,[300,500,700])
rice['much'] = fuzz.trimf(rice.universe,[500,700,1000])
rice['very much'] = fuzz.trimf(rice.universe,[700,1000,1000])
power['very small'] = fuzz.trimf(power.universe,[0,20,35])
power['small'] = fuzz.trimf(power.universe,[20,35,50])
power['medium'] = fuzz.trimf(power.universe,[35,50,65])
power['big'] = fuzz.trimf(power.universe,[50,65,80])
power['very big'] = fuzz.trimf(power.universe,[65,80,100])
time.view()
rice.view()
power.view()

rule1 =  ctrl.Rule( time['very slow'] & rice['few'], power['very small'])
rule2 =  ctrl.Rule( time['very slow'] & rice['little'], power['very small'])
rule3 =  ctrl.Rule( time['very slow'] & rice['medium'], power['small'])
rule4 =  ctrl.Rule( time['very slow'] & rice['much'], power['small'])
rule5 =  ctrl.Rule( time['very slow'] & rice['very much'], power['medium'])
rule6 =  ctrl.Rule( time['slow'] & rice['few'], power['very small'])
rule7 =  ctrl.Rule( time['slow'] & rice['little'], power['very small'])
rule8 =  ctrl.Rule( time['slow'] & rice['medium'], power['small'])
rule9 =  ctrl.Rule( time['slow'] & rice['much'], power['medium'])
rule10 =  ctrl.Rule( time['slow'] & rice['very much'], power['medium'])
rule11 =  ctrl.Rule( time['medium'] & rice['few'], power['very small'])
rule12 =  ctrl.Rule( time['medium'] & rice['little'], power['small'])
rule13 =  ctrl.Rule( time['medium'] & rice['medium'], power['medium'])
rule14 =  ctrl.Rule( time['medium'] & rice['much'], power['big'])
rule15 =  ctrl.Rule( time['medium'] & rice['very much'], power['very big'])
rule16 =  ctrl.Rule( time['fast'] & rice['few'], power['small'])
rule17 =  ctrl.Rule( time['fast'] & rice['little'], power['medium'])
rule18 =  ctrl.Rule( time['fast'] & rice['medium'], power['big'])
rule19 =  ctrl.Rule( time['fast'] & rice['much'], power['very big'])
rule20 =  ctrl.Rule( time['fast'] & rice['very much'], power['very big'])
rule21 =  ctrl.Rule( time['very fast'] & rice['few'], power['big'])
rule22 =  ctrl.Rule( time['very fast'] & rice['little'], power['big'])
rule23 =  ctrl.Rule( time['very fast'] & rice['medium'], power['very big'])
rule24 =  ctrl.Rule( time['very fast'] & rice['much'], power['very big'])
rule25 =  ctrl.Rule( time['very fast'] & rice['very much'], power['very big'])
powering_ctrl = ctrl.ControlSystem([rule1,rule2,rule3,rule4,rule5,rule6,rule7,rule8,rule9,rule10,rule11,rule12,rule13,rule14,rule15,rule16,rule17,rule18,rule19,rule20,rule21,rule22,rule23,rule24,rule25])
powering = ctrl.ControlSystemSimulation(powering_ctrl)
powering.input['time'] = 100
powering.input['rice'] = 100
powering.compute()
print(powering.output['power'])
power.view(sim=powering)

